"""buckinghampi.py: a symbolic module that generates the pi terms based on some variables by applying the pi-theorem."""

from __future__ import annotations

__author__ = "Mokbel Karam"
__copyright__ = "Copyright (c) 2021, Mokbel Karam"

__credits__ = ["University of Utah Department of Chemical Engineering"]
__license__ = "MIT"
__version__ = "1.0.3"
__maintainer__ = "Mokbel Karam"
__email__ = "karammokbel@gmail.com"
__status__ = "Production"

import concurrent.futures
import logging
import multiprocessing
from itertools import combinations
from typing import Dict, TypeAlias, List, Callable, Tuple, Protocol

import numpy as np
import sympy as sp
import tqdm
from sympy.core.expr import Expr
from sympy.core.mul import Mul, Pow
from sympy.parsing.sympy_parser import parse_expr
from tabulate import tabulate

try:
    from IPython.display import display, clear_output, Math, Markdown
except:
    pass

logger = logging.getLogger("buckinghampy")

# Types for individual pi group and list of groups, i.e., a pi set
PiType: TypeAlias = sp.Expr
PiSetType: TypeAlias = List[PiType]


class ConstraintFnType(Protocol):
    def __call__(self, pi_set: PiSetType, **kwargs) -> bool:
        """Check if pi_set is valid according to some constraint. Return True if valid, False otherwise."""


def find_duplicates_worker(pi_set: PiSetType, other: PiSetType) -> List[PiSetType]:
    """Check if pi_set is a duplicate of other using a bipartite matching algorithm.
    Generated by Claude 3.7. Equivalence with original code tested until 10 variables (see test_speedup.py).
    """
    if len(pi_set) != len(other):
        return []

    # Quick filter: Check if sets contain the same variables
    pi_vars = set()
    other_vars = set()
    for pi in pi_set:
        pi_vars.update(pi.free_symbols)
    for o in other:
        other_vars.update(o.free_symbols)
    if pi_vars != other_vars:
        return []

    # Check if pi_term and other_term are equivalent (directly or inversely)
    def is_equivalent(pi_term, other_term):
        product = pi_term * other_term
        inverse_product = pi_term * (other_term ** (-1))
        return isinstance(product, sp.Number) or isinstance(inverse_product, sp.Number)

    # Precompute all equivalences for faster lookup
    equivalences = {}
    for i, pi_term in enumerate(pi_set):
        equivalences[i] = []
        for j, other_term in enumerate(other):
            if is_equivalent(pi_term, other_term):
                equivalences[i].append(j)

    # Quick check: If any pi term has no equivalence, the sets can't be duplicates
    if any(not eq for eq in equivalences.values()):
        return []

    # Try to find a valid mapping recursively
    def find_valid_mapping(used_indices=None, remaining_indices=None):
        if used_indices is None:
            used_indices = set()
        if remaining_indices is None:
            remaining_indices = list(range(len(pi_set)))

        # If we've mapped all pi terms, we found a valid mapping
        if not remaining_indices:
            return True

        # Choose the pi term with the fewest possible matches first (critical optimization)
        remaining_indices.sort(key=lambda i: len(equivalences[i]))
        chosen_index = remaining_indices[0]

        # Try each possible match for the chosen pi term
        for j in equivalences[chosen_index]:
            if j not in used_indices:
                used_indices.add(j)
                new_remaining = [i for i in remaining_indices if i != chosen_index]
                if find_valid_mapping(used_indices, new_remaining):
                    return True
                used_indices.remove(j)

        return False

    if find_valid_mapping():
        return [pi_set]
    else:
        return []


class BuckinghamPi:
    def __init__(self, n_jobs: int = 1, var_max_sets: int | None = None):
        """
        Construct an instance of the BuckinghamPi theorem
        """
        self._var_from_idx = {}
        self._idx_from_var = {}
        self._variables = {}
        self._sym_variables = {}
        self._flagged_var = {"var_name": None, "var_index": None, "selected": False}

        self._null_spaces = []

        self._fundamental_vars_used = []  # list of fundamental variables being used

        self._prefixed_dimensionless_terms = []

        if (n_jobs == -1) or (n_jobs is None):
            self.n_jobs = multiprocessing.cpu_count()
        else:
            self.n_jobs = n_jobs

        self._flagged_var_max_sets = var_max_sets
        self._constraint_fns: List[Tuple[Callable, Dict]] = []

    @property
    def fundamental_variables(self):
        """
        :return: a list of the fundamental variables being used
        """
        return self._fundamental_vars_used

    @property
    def variables(self):
        """
        :return: a dict of the variables added by the user.
        """
        return self._variables

    def _parse_expression(self, string: str):
        if "^" in string:
            # convert the xor operator to power operator
            string = string.replace("^", "**")

        expr = parse_expr(string.lower())

        if not (isinstance(expr, Mul) or isinstance(expr, Pow) or isinstance(expr, sp.Symbol)):
            raise Exception(
                "expression of type {} is not of the accepted types ({}, {}, {})".format(
                    type(expr), Mul, Pow, sp.Symbol
                )
            )
        if expr.as_coeff_Mul()[0] != 1:
            raise Exception(
                "cannot have coefficients, {}, that multiply the expression {}".format(
                    expr.as_coeff_Mul()[0], expr.as_coeff_Mul()[1]
                )
            )

        # Make sure dimensions only contain integer exponents
        # Technically this only checks for *any* rational number in the expression,
        # but units should only be expressions made up of a dimension and an exponent, so implicitly this is fine.
        has_non_int_exp = any([not a.is_Integer for a in expr.atoms() if not a.is_Symbol])
        if has_non_int_exp:
            raise ValueError(f"Dimension {expr} contains non-integer exponent(s), which is not allowed.")

        # extract the physical dimensions from the dimensions expressions
        used_symbols = list(expr.free_symbols)
        for sym in used_symbols:
            if not sym in self._fundamental_vars_used:
                self._fundamental_vars_used.append(sym)

        return expr

    def _extract_exponents(self, expr: Expr):
        num_physical_dimensions = len(self._fundamental_vars_used)
        vect = np.zeros(num_physical_dimensions)
        args = list(expr.args) if list(expr.args) else [expr]
        # print(args)
        if isinstance(expr, Pow):
            vect[self._fundamental_vars_used.index(args[0])] = int(args[1])
        else:
            for e in args:
                if isinstance(expr, sp.Symbol):
                    vect[self._fundamental_vars_used.index(e)] = int(1)
                    # print('({}, {})'.format(e, 1))
                else:
                    var, exponent = e.as_base_exp()
                    vect[self._fundamental_vars_used.index(var)] = int(exponent)
                    # print('({}, {})'.format(var, exponent))

        return vect

    def add_variable(self, name: str, dimensions: str, non_repeating=False):
        """
        Add variables to use for the pi-theorem
        :param name: (string) name of the variable to be added
        :param dimensions: (string) expression of the independent physical variable expressed in terms of the k independent fundamental dimensions.
        :param non_repeating: (boolean) select a variable to belong to the non-repeating variables matrix. This will ensure that the selected variable
                                        only shows up in one dimensionless group.
        """
        if dimensions != "1":
            expr = self._parse_expression(dimensions)

            self._variables.update({name: expr})
            var_idx = len(list(self._variables.keys())) - 1
            self._var_from_idx[var_idx] = name
            self._idx_from_var[name] = var_idx
            if non_repeating and (self._flagged_var["selected"] == False):
                self._flagged_var["var_name"] = name
                self._flagged_var["var_index"] = var_idx
                self._flagged_var["selected"] = True
            elif non_repeating and (self._flagged_var["selected"] == True):
                raise Exception("you cannot select more than one variable at a time to be a non_repeating.")
        else:
            self._prefixed_dimensionless_terms.append(sp.symbols(name))

    def add_pi_set_constraint(self, constraint_fn: ConstraintFnType, **fn_kwargs):
        """
        Add a constraint to the pi sets. The function should return True if the pi set is valid, False otherwise.
        """
        self._constraint_fns.append((constraint_fn, fn_kwargs))

    def _create_M(self):
        logger.info("Creating M matrix")
        self.num_variable = len(list(self._variables.keys()))
        num_physical_dimensions = len(self._fundamental_vars_used)
        if self.num_variable <= num_physical_dimensions:
            raise Exception("The number of variables has to be greater than the number of physical dimensions.")

        self.M = np.zeros(shape=(self.num_variable, num_physical_dimensions))
        # fill M
        for var_name in self._variables.keys():
            expr = self._variables[var_name]
            vect = self._extract_exponents(expr)
            row = self._idx_from_var[var_name]
            self.M[row, :] = vect

        self.M = self.M.transpose()

    def _create_symbolic_variables(self):
        logger.info("Creating symbolic variables")
        for var_name in self._variables.keys():
            self._sym_variables[var_name] = sp.symbols(var_name)

    def _solve_null_spaces(self):
        logger.info("Solving null spaces")
        if self._flagged_var["selected"] == True:
            self._solve_null_spaces_for_flagged_variables()

        else:
            for idx in self._var_from_idx.keys():
                self._flagged_var["var_name"] = self._var_from_idx[idx]
                self._flagged_var["var_index"] = idx
                self._flagged_var["selected"] = True

                self._solve_null_spaces_for_flagged_variables()

    def _solve_null_spaces_for_flagged_variables(self):

        assert self._flagged_var["selected"] == True, " you need to select a variable to be explicit"

        n = self.num_variable
        m = len(self._fundamental_vars_used)

        original_indicies = list(range(0, n))
        all_idx = original_indicies.copy()
        if self._flagged_var["selected"]:
            del all_idx[self._flagged_var["var_index"]]

        # print(all_idx)
        all_combs = list(combinations(all_idx, m))[: self._flagged_var_max_sets]
        # print(all_combs)

        num_det_0 = 0
        for comb in all_combs:
            temp_comb = list(comb).copy()
            extra_vars = [i for i in original_indicies if i not in temp_comb]
            b_ns = []
            for extra_var in extra_vars:
                new_order = {}
                temp_comb.append(extra_var)
                A = self.M[:, temp_comb].copy()
                for num, var_idx in enumerate(temp_comb):
                    new_order[num] = self._var_from_idx[var_idx]
                B = sp.Matrix(A)
                test_mat = B[:, :m]
                if sp.det(test_mat) != 0:
                    ns = B.nullspace()[0]
                    b_ns.append({"order": new_order, "power": ns.tolist()})

                else:
                    num_det_0 += 1
                temp_comb = list(comb).copy()
            if b_ns:  # if b_ns is not empty add it to the nullspaces list
                self._null_spaces.append(b_ns)
        # print("num of det 0 : ",num_det_0)

    def _construct_symbolic_pi_terms(self):
        logger.info("Constructing symbolic pi terms")
        self._allpiterms = []
        for space in self._null_spaces:
            spacepiterms = []
            for term in space:
                expr = 1
                idx = 0
                for order, power in zip(term["order"].keys(), term["power"]):
                    expr *= self._sym_variables[term["order"][order]] ** sp.nsimplify(sp.Rational(power[0]))
                    idx += 1
                spacepiterms.append(expr)
            # check for already existing pi terms in previous null-spaces
            already_exists = False
            for previouspiterms in self._allpiterms:
                if all(x in previouspiterms for x in spacepiterms):
                    already_exists = True
                    break
            if not already_exists:
                self._allpiterms.append(spacepiterms)

    def _apply_pi_term_constraints(self):

        logger.info(f"Applying pi set constraints ({[fn.__name__ for fn, _ in self._constraint_fns]})")
        n_before_constraints = len(self._allpiterms)
        is_valid = [
            all([fn(pi_set, **fn_kwargs) for fn, fn_kwargs in self._constraint_fns]) for pi_set in self._allpiterms
        ]
        self._allpiterms = [pi_set for pi_set, valid in zip(self._allpiterms, is_valid) if valid]
        logger.info(
            f"-> Reduced from {n_before_constraints} to {len(self._allpiterms)} " f"pi sets after applying constraints"
        )

    def _rm_duplicated_powers(self):
        logger.info(f"Removing duplicated Pi sets. Starting with {len(self._allpiterms)} sets.")
        # this algorithm rely on the fact that the nullspace function
        # in sympy set one free variable to 1 and the all other to zero
        # then solve the system by back substitution.
        duplicate = []
        dummy_other_terms = self._allpiterms.copy()

        futures = []
        with concurrent.futures.ProcessPoolExecutor(max_workers=self.n_jobs) as executor:
            for num_set, pi_set in enumerate(self._allpiterms):
                dummy_other_terms.remove(pi_set)
                for num_other, other in enumerate(dummy_other_terms):
                    futures.append(executor.submit(find_duplicates_worker, pi_set, other))

            for future in tqdm.tqdm(concurrent.futures.as_completed(futures), total=len(futures)):
                duplicate.extend(future.result())

        # remove duplicates from the main dict of all pi terms
        for dup in duplicate:
            if dup in self._allpiterms:
                self._allpiterms.remove(dup)

        logger.info(f"-> Reduced to {len(self._allpiterms)} sets after removing duplicates.")
        return duplicate

    def _populate_prefixed_dimensionless_groups(self):
        for num_set, pi_set in enumerate(self._allpiterms):
            for pre_fixed_dimensionless_group in self._prefixed_dimensionless_terms:
                self._allpiterms[num_set].append(pre_fixed_dimensionless_group)

    def generate_pi_terms(self):
        """
        Generates all the possible pi terms
        """
        self._create_M()

        self._create_symbolic_variables()

        self._solve_null_spaces()

        self._construct_symbolic_pi_terms()

        self._apply_pi_term_constraints()

        self._rm_duplicated_powers()

        self._populate_prefixed_dimensionless_groups()
        logger.info("Done!")

    @property
    def pi_terms(self):
        """
        :return: a list with all the symbolic dimensionless terms for all permutation of the dimensional Matrix M
        """
        return self._allpiterms

    def _jupyter_print(self):
        """print the rendered Latex format in Jupyter cell"""
        for set_num, space in enumerate(self._allpiterms):
            latex_str = "\\text{Set }"
            latex_str += "{}: \\quad".format(set_num + 1)
            for num, term in enumerate(space):
                latex_str += "\\pi_{} = ".format(num + 1) + sp.latex(term)
                latex_str += "\\quad"
            display(Math(latex_str))
            display(Markdown("---"))

    def _get_latex_form(self, latex_string=False):
        latex_form = []
        for pi_set in self._allpiterms:
            latex_set = []
            for pi in pi_set:
                if latex_string:
                    if latex_string:
                        latex_set.append(sp.latex(pi))
                    else:
                        latex_set.append(pi)
                else:
                    latex_set.append(pi)
            latex_form.append(latex_set)

        num_of_pi_terms = len(latex_form[0])

        headers = ["sets"]
        for num in range(num_of_pi_terms):
            headers.append("Pi {}".format(num + 1))

        for num, set in enumerate(latex_form):
            set.insert(0, num + 1)

        return latex_form

    def _tabulate_print(self, latex_string=False):
        """print the dimensionless sets in a tabulated format"""
        print(tabulate(self._get_latex_form(latex_string), headers=headers))

    def print_all(self, latex_string=False):
        """
        print all the sets of dimensionless groups in latex or symbolic form.
        :latex_string: optional boolean. If set to True the function will print the latex string of the
                        dimensionless groups. if set to False the function will print the symbolic form of the
                        dimensionless groups.
        """
        try:
            """Try to render the latex in Jupyter cell"""
            self._jupyter_print()
        except:
            """print the dimensionless sets in a tabulated format when in terminal session"""
            self._tabulate_print(latex_string)

    def return_all(self, latex_string=False):
        """return all of the latex output in a dict for easier downstream processing"""
        return self._get_latex_form(latex_string)
